const buttonOpen = document.querySelector('.open')
const buttonClose = document.querySelector(".close")
const options = document.querySelector('.options')
const logo = document.querySelector('.logo')
const buttonAboutMe = document.querySelector('.sobre-mim')
const buttonWorks = document.querySelector(".trabalhos")
const buttonContact = document.querySelector(".contato")
buttonOpen.addEventListener('click', () => {
  options.classList.add('show')
  buttonClose.classList.add('show')
  buttonOpen.classList.add('close')
  logo.classList.add('close')
})
buttonClose.addEventListener('click', () => {
  options.classList.remove("show")
  buttonClose.classList.remove("show")
  buttonOpen.classList.remove("close")
  logo.classList.remove("close")
})
buttonAboutMe.addEventListener("click", () => {
  options.classList.remove("show")
  buttonClose.classList.remove("show")
  buttonOpen.classList.remove("close")
  logo.classList.remove("close")
})
buttonWorks.addEventListener("click", () => {
  options.classList.remove("show")
  buttonClose.classList.remove("show")
  buttonOpen.classList.remove("close")
  logo.classList.remove("close")
})
buttonContact.addEventListener("click", () => {
  options.classList.remove("show")
  buttonClose.classList.remove("show")
  buttonOpen.classList.remove("close")
  logo.classList.remove("close")
})